/**
 * Test Fixtures for Boundaries
 * Sample data for testing boundary search functionality
 */

export const mockBoundaryTypes = [
  {
    id: "type-region",
    code: "region",
    name: "Region",
    localName: "Région",
    level: 1,
    countryCode: "BE",
  },
  {
    id: "type-province",
    code: "province",
    name: "Province",
    localName: "Province",
    level: 2,
    countryCode: "BE",
  },
  {
    id: "type-municipality",
    code: "municipality",
    name: "Municipality",
    localName: "Commune",
    level: 3,
    countryCode: "BE",
  },
];

export const mockBoundaries = [
  {
    id: "boundary-1",
    name: "Brussels",
    nameSlug: "brussels",
    alternateNames: ["Bruxelles", "Brussel"],
    boundaryTypeId: "type-region",
    boundaryType: mockBoundaryTypes[0],
    country_code: "BE",
    centroidLat: 50.8503,
    centroidLon: 4.3517,
    population: 1218255,
    area_sqkm: 161.38,
    isPopular: true,
    searchRank: 100,
    minLat: 50.7,
    maxLat: 51.0,
    minLon: 4.2,
    maxLon: 4.5,
  },
  {
    id: "boundary-2",
    name: "Antwerp",
    nameSlug: "antwerp",
    alternateNames: ["Antwerpen"],
    boundaryTypeId: "type-province",
    boundaryType: mockBoundaryTypes[1],
    country_code: "BE",
    centroidLat: 51.2194,
    centroidLon: 4.4025,
    population: 1857986,
    area_sqkm: 2867,
    isPopular: true,
    searchRank: 90,
    minLat: 50.9,
    maxLat: 51.5,
    minLon: 4.1,
    maxLon: 4.7,
  },
  {
    id: "boundary-3",
    name: "Ghent",
    nameSlug: "ghent",
    alternateNames: ["Gent"],
    boundaryTypeId: "type-municipality",
    boundaryType: mockBoundaryTypes[2],
    country_code: "BE",
    centroidLat: 51.0543,
    centroidLon: 3.7174,
    population: 262219,
    area_sqkm: 156.18,
    isPopular: true,
    searchRank: 95,
    minLat: 50.9,
    maxLat: 51.2,
    minLon: 3.5,
    maxLon: 3.9,
  },
  {
    id: "boundary-4",
    name: "Bruges",
    nameSlug: "bruges",
    alternateNames: ["Brugge"],
    boundaryTypeId: "type-municipality",
    boundaryType: mockBoundaryTypes[2],
    country_code: "BE",
    centroidLat: 51.2093,
    centroidLon: 3.2247,
    population: 118284,
    area_sqkm: 138.4,
    isPopular: true,
    searchRank: 90,
    minLat: 51.1,
    maxLat: 51.3,
    minLon: 3.1,
    maxLon: 3.4,
  },
  {
    id: "boundary-5",
    name: "Liège",
    nameSlug: "liege",
    alternateNames: ["Luik"],
    boundaryTypeId: "type-municipality",
    boundaryType: mockBoundaryTypes[2],
    country_code: "BE",
    centroidLat: 50.6326,
    centroidLon: 5.5797,
    population: 197355,
    area_sqkm: 69.39,
    isPopular: true,
    searchRank: 90,
    minLat: 50.5,
    maxLat: 50.7,
    minLon: 5.4,
    maxLon: 5.7,
  },
];
